name: 🚀 1.0 Preview Feedback
description: Share your feedback on the Arcane 1.0 Preview release!
title: '🚀 1.0 Preview Feedback: '
labels: ['v1.0-feedback']
body:
  - type: markdown
    attributes:
      value: |
        Thank you for trying the Arcane 1.0 Preview!  
        Please share your thoughts, suggestions, and any issues you encountered.

  - type: textarea
    id: feedback
    attributes:
      label: Feedback & Suggestions
      description: Tell us what you think! What works well? What could be improved? Any missing features?
      placeholder: I love the new dashboard, but I wish...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps To Reproduce (if reporting an issue)
      description: If you encountered a problem, please describe how to reproduce it.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. See issue
    validations:
      required: false

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior (if reporting an issue)
      description: What did you expect to happen?
      placeholder: I expected the page to load a new view...
    validations:
      required: false

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior (if reporting an issue)
      description: What actually happened?
      placeholder: Instead, I got an error message saying...
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Add screenshots or recordings if they help explain your feedback.
      placeholder: Paste screenshots here...
    validations:
      required: false

  - type: input
    id: version
    attributes:
      label: Arcane Version
      description: What version of Arcane are you using?
      placeholder: v1.0.0-preview
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - macOS
        - Windows
        - Linux
        - Other
    validations:
      required: true

  - type: input
    id: browser
    attributes:
      label: Browser
      description: What browser are you using?
      placeholder: Chrome 124, Firefox 125, etc.
    validations:
      required: false

  - type: input
    id: docker
    attributes:
      label: Docker Version
      description: What Docker version are you using?
      placeholder: 25.0.0
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other comments or context?
      placeholder: Any other relevant information...
    validations:
      required: false
