name: ⚡️ Feature Request
description: Suggest a new feature or enhancement for Arcane
title: '⚡️ Feature: '
labels: ['enhancement']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature!

  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: A clear and concise description of the feature you'd like to see implemented.
      placeholder: I would like to see...
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem It Solves
      description: Explain what problem this feature solves or what need it addresses.
      placeholder: This would help with...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe how you envision this feature working.
      placeholder: I think this could work by...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: I've tried doing... but it doesn't quite work because...
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other information, mockups, or examples that might help illustrate the feature request.
      placeholder: Here are some examples of similar features in other products...
    validations:
      required: false

  - type: checkboxes
    id: contribute
    attributes:
      label: Would you be willing to work on this feature?
      options:
        - label: Yes, I'd like to implement this feature
        - label: I could help with parts of this feature
        - label: No, I'm just suggesting the feature
    validations:
      required: true
