name: Run ESLint

on:
  push:
    branches: [main]
    paths:
      - 'src/**'
      - '.github/workflows/eslint.yml'
      - 'package.json'
      - 'package-lock.json'
      - '.eslintrc.cjs'
      - 'tsconfig.json'
  pull_request:
    branches: [main]
    paths:
      - 'src/**'
      - '.github/workflows/eslint.yml'
      - 'package.json'
      - 'package-lock.json'
      - '.eslintr.config.js'
      - 'tsconfig.json'
  workflow_dispatch:

jobs:
  lint:
    name: Run ESLint
    if: github.actor != 'dependabot[bot]'
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Setup problem matcher
        run: echo "::add-matcher::.github/eslint-matcher.json"

      - name: Run ESLint
        run: npm run lint
